/*
 * Created on 5 Jun 2016 ( Time 14:55:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.mynfl.domain.DraftType;
import com.kumasi.mynfl.domain.jpa.DraftTypeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class DraftTypeServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public DraftTypeServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'DraftTypeEntity' to 'DraftType'
	 * @param draftTypeEntity
	 */
	public DraftType mapDraftTypeEntityToDraftType(DraftTypeEntity draftTypeEntity) {
		if(draftTypeEntity == null) {
			return null;
		}

		//--- Generic mapping 
		DraftType draftType = map(draftTypeEntity, DraftType.class);

		return draftType;
	}
	
	/**
	 * Mapping from 'DraftType' to 'DraftTypeEntity'
	 * @param draftType
	 * @param draftTypeEntity
	 */
	public void mapDraftTypeToDraftTypeEntity(DraftType draftType, DraftTypeEntity draftTypeEntity) {
		if(draftType == null) {
			return;
		}

		//--- Generic mapping 
		map(draftType, draftTypeEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}