/*
 * Created on 5 Jun 2016 ( Time 14:55:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.mynfl.domain.DraftRound;
import com.kumasi.mynfl.domain.jpa.DraftRoundEntity;
import com.kumasi.mynfl.domain.jpa.DraftTeamEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class DraftRoundServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public DraftRoundServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'DraftRoundEntity' to 'DraftRound'
	 * @param draftRoundEntity
	 */
	public DraftRound mapDraftRoundEntityToDraftRound(DraftRoundEntity draftRoundEntity) {
		if(draftRoundEntity == null) {
			return null;
		}

		//--- Generic mapping 
		DraftRound draftRound = map(draftRoundEntity, DraftRound.class);

		//--- Link mapping ( link to DraftTeam )
		if(draftRoundEntity.getDraftTeam() != null) {
			draftRound.setDraftTeamId(draftRoundEntity.getDraftTeam().getId());
		}
		return draftRound;
	}
	
	/**
	 * Mapping from 'DraftRound' to 'DraftRoundEntity'
	 * @param draftRound
	 * @param draftRoundEntity
	 */
	public void mapDraftRoundToDraftRoundEntity(DraftRound draftRound, DraftRoundEntity draftRoundEntity) {
		if(draftRound == null) {
			return;
		}

		//--- Generic mapping 
		map(draftRound, draftRoundEntity);

		//--- Link mapping ( link : draftRound )
		if( hasLinkToDraftTeam(draftRound) ) {
			DraftTeamEntity draftTeam1 = new DraftTeamEntity();
			draftTeam1.setId( draftRound.getDraftTeamId() );
			draftRoundEntity.setDraftTeam( draftTeam1 );
		} else {
			draftRoundEntity.setDraftTeam( null );
		}

	}
	
	/**
	 * Verify that DraftTeam id is valid.
	 * @param DraftTeam DraftTeam
	 * @return boolean
	 */
	private boolean hasLinkToDraftTeam(DraftRound draftRound) {
		if(draftRound.getDraftTeamId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}