/*
 * Created on 5 Jun 2016 ( Time 14:55:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.mynfl.domain.PlayerPosition;
import com.kumasi.mynfl.domain.jpa.PlayerPositionEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PlayerPositionServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PlayerPositionServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PlayerPositionEntity' to 'PlayerPosition'
	 * @param playerPositionEntity
	 */
	public PlayerPosition mapPlayerPositionEntityToPlayerPosition(PlayerPositionEntity playerPositionEntity) {
		if(playerPositionEntity == null) {
			return null;
		}

		//--- Generic mapping 
		PlayerPosition playerPosition = map(playerPositionEntity, PlayerPosition.class);

		return playerPosition;
	}
	
	/**
	 * Mapping from 'PlayerPosition' to 'PlayerPositionEntity'
	 * @param playerPosition
	 * @param playerPositionEntity
	 */
	public void mapPlayerPositionToPlayerPositionEntity(PlayerPosition playerPosition, PlayerPositionEntity playerPositionEntity) {
		if(playerPosition == null) {
			return;
		}

		//--- Generic mapping 
		map(playerPosition, playerPositionEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}