/*
 * Created on 5 Jun 2016 ( Time 14:55:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.mynfl.domain.ScheduleType;
import com.kumasi.mynfl.domain.jpa.ScheduleTypeEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ScheduleTypeServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ScheduleTypeServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ScheduleTypeEntity' to 'ScheduleType'
	 * @param scheduleTypeEntity
	 */
	public ScheduleType mapScheduleTypeEntityToScheduleType(ScheduleTypeEntity scheduleTypeEntity) {
		if(scheduleTypeEntity == null) {
			return null;
		}

		//--- Generic mapping 
		ScheduleType scheduleType = map(scheduleTypeEntity, ScheduleType.class);

		return scheduleType;
	}
	
	/**
	 * Mapping from 'ScheduleType' to 'ScheduleTypeEntity'
	 * @param scheduleType
	 * @param scheduleTypeEntity
	 */
	public void mapScheduleTypeToScheduleTypeEntity(ScheduleType scheduleType, ScheduleTypeEntity scheduleTypeEntity) {
		if(scheduleType == null) {
			return;
		}

		//--- Generic mapping 
		map(scheduleType, scheduleTypeEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}