/*
 * Created on 5 Jun 2016 ( Time 14:55:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.mynfl.domain.jpa.ConferenceEntity;
import com.kumasi.mynfl.persistence.commons.fake.GenericFakeService;
import com.kumasi.mynfl.persistence.services.ConferencePersistence;

/**
 * Fake persistence service implementation ( entity "Conference" )
 *
 * @author Telosys Tools Generator
 */
public class ConferencePersistenceFAKE extends GenericFakeService<ConferenceEntity> implements ConferencePersistence {

	public ConferencePersistenceFAKE () {
		super(ConferenceEntity.class);
	}
	
	protected ConferenceEntity buildEntity(int index) {
		ConferenceEntity entity = new ConferenceEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setCode( nextString() ) ;
		entity.setName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(ConferenceEntity entity) {
		log("delete ( ConferenceEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(ConferenceEntity entity) {
		log("insert ( ConferenceEntity : " + entity + ")" ) ;
	}

	public ConferenceEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<ConferenceEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<ConferenceEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<ConferenceEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public ConferenceEntity save(ConferenceEntity entity) {
		log("insert ( ConferenceEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<ConferenceEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
