/*
 * Created on 5 Jun 2016 ( Time 14:55:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.mynfl.domain.jpa.DraftEntity;
import com.kumasi.mynfl.persistence.commons.fake.GenericFakeService;
import com.kumasi.mynfl.persistence.services.DraftPersistence;

/**
 * Fake persistence service implementation ( entity "Draft" )
 *
 * @author Telosys Tools Generator
 */
public class DraftPersistenceFAKE extends GenericFakeService<DraftEntity> implements DraftPersistence {

	public DraftPersistenceFAKE () {
		super(DraftEntity.class);
	}
	
	protected DraftEntity buildEntity(int index) {
		DraftEntity entity = new DraftEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setYear( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(DraftEntity entity) {
		log("delete ( DraftEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(DraftEntity entity) {
		log("insert ( DraftEntity : " + entity + ")" ) ;
	}

	public DraftEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<DraftEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<DraftEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<DraftEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public DraftEntity save(DraftEntity entity) {
		log("insert ( DraftEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<DraftEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
