/*
 * Created on 5 Jun 2016 ( Time 14:55:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.mynfl.domain.jpa.DraftTeamEntity;
import com.kumasi.mynfl.persistence.commons.fake.GenericFakeService;
import com.kumasi.mynfl.persistence.services.DraftTeamPersistence;

/**
 * Fake persistence service implementation ( entity "DraftTeam" )
 *
 * @author Telosys Tools Generator
 */
public class DraftTeamPersistenceFAKE extends GenericFakeService<DraftTeamEntity> implements DraftTeamPersistence {

	public DraftTeamPersistenceFAKE () {
		super(DraftTeamEntity.class);
	}
	
	protected DraftTeamEntity buildEntity(int index) {
		DraftTeamEntity entity = new DraftTeamEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setTeamCode( nextString() ) ;
		entity.setTeamName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(DraftTeamEntity entity) {
		log("delete ( DraftTeamEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(DraftTeamEntity entity) {
		log("insert ( DraftTeamEntity : " + entity + ")" ) ;
	}

	public DraftTeamEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<DraftTeamEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<DraftTeamEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<DraftTeamEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public DraftTeamEntity save(DraftTeamEntity entity) {
		log("insert ( DraftTeamEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<DraftTeamEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
