/*
 * Created on 5 Jun 2016 ( Time 14:55:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.mynfl.domain.jpa.DraftTypeEntity;
import com.kumasi.mynfl.persistence.commons.fake.GenericFakeService;
import com.kumasi.mynfl.persistence.services.DraftTypePersistence;

/**
 * Fake persistence service implementation ( entity "DraftType" )
 *
 * @author Telosys Tools Generator
 */
public class DraftTypePersistenceFAKE extends GenericFakeService<DraftTypeEntity> implements DraftTypePersistence {

	public DraftTypePersistenceFAKE () {
		super(DraftTypeEntity.class);
	}
	
	protected DraftTypeEntity buildEntity(int index) {
		DraftTypeEntity entity = new DraftTypeEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setCode( nextString() ) ;
		entity.setName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(DraftTypeEntity entity) {
		log("delete ( DraftTypeEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(DraftTypeEntity entity) {
		log("insert ( DraftTypeEntity : " + entity + ")" ) ;
	}

	public DraftTypeEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<DraftTypeEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<DraftTypeEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<DraftTypeEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public DraftTypeEntity save(DraftTypeEntity entity) {
		log("insert ( DraftTypeEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<DraftTypeEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
