/*
 * Created on 5 Jun 2016 ( Time 14:55:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.mynfl.domain.jpa.PlayerPositionEntity;
import com.kumasi.mynfl.persistence.commons.fake.GenericFakeService;
import com.kumasi.mynfl.persistence.services.PlayerPositionPersistence;

/**
 * Fake persistence service implementation ( entity "PlayerPosition" )
 *
 * @author Telosys Tools Generator
 */
public class PlayerPositionPersistenceFAKE extends GenericFakeService<PlayerPositionEntity> implements PlayerPositionPersistence {

	public PlayerPositionPersistenceFAKE () {
		super(PlayerPositionEntity.class);
	}
	
	protected PlayerPositionEntity buildEntity(int index) {
		PlayerPositionEntity entity = new PlayerPositionEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setPositionName( nextString() ) ;
		entity.setDescription( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(PlayerPositionEntity entity) {
		log("delete ( PlayerPositionEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(PlayerPositionEntity entity) {
		log("insert ( PlayerPositionEntity : " + entity + ")" ) ;
	}

	public PlayerPositionEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<PlayerPositionEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<PlayerPositionEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<PlayerPositionEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public PlayerPositionEntity save(PlayerPositionEntity entity) {
		log("insert ( PlayerPositionEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<PlayerPositionEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
