/*
 * Created on 5 Jun 2016 ( Time 14:55:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.mynfl.domain.jpa.ScheduleTypeEntity;
import com.kumasi.mynfl.persistence.commons.fake.GenericFakeService;
import com.kumasi.mynfl.persistence.services.ScheduleTypePersistence;

/**
 * Fake persistence service implementation ( entity "ScheduleType" )
 *
 * @author Telosys Tools Generator
 */
public class ScheduleTypePersistenceFAKE extends GenericFakeService<ScheduleTypeEntity> implements ScheduleTypePersistence {

	public ScheduleTypePersistenceFAKE () {
		super(ScheduleTypeEntity.class);
	}
	
	protected ScheduleTypeEntity buildEntity(int index) {
		ScheduleTypeEntity entity = new ScheduleTypeEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setCode( nextString() ) ;
		entity.setDescription( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(ScheduleTypeEntity entity) {
		log("delete ( ScheduleTypeEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(ScheduleTypeEntity entity) {
		log("insert ( ScheduleTypeEntity : " + entity + ")" ) ;
	}

	public ScheduleTypeEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<ScheduleTypeEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<ScheduleTypeEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<ScheduleTypeEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public ScheduleTypeEntity save(ScheduleTypeEntity entity) {
		log("insert ( ScheduleTypeEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<ScheduleTypeEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
