/*
 * Created on 5 Jun 2016 ( Time 14:55:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.kumasi.mynfl.domain.jpa.StatusEntity;
import com.kumasi.mynfl.persistence.commons.fake.GenericFakeService;
import com.kumasi.mynfl.persistence.services.StatusPersistence;

/**
 * Fake persistence service implementation ( entity "Status" )
 *
 * @author Telosys Tools Generator
 */
public class StatusPersistenceFAKE extends GenericFakeService<StatusEntity> implements StatusPersistence {

	public StatusPersistenceFAKE () {
		super(StatusEntity.class);
	}
	
	protected StatusEntity buildEntity(int index) {
		StatusEntity entity = new StatusEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setCode( nextString() ) ;
		entity.setName( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(StatusEntity entity) {
		log("delete ( StatusEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(StatusEntity entity) {
		log("insert ( StatusEntity : " + entity + ")" ) ;
	}

	public StatusEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<StatusEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<StatusEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<StatusEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public StatusEntity save(StatusEntity entity) {
		log("insert ( StatusEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<StatusEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
