/*
 * Created on 5 Jun 2016 ( Time 14:55:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.kumasi.mynfl.domain.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "Division"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="Division", catalog="nfldb" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DivisionEntity.countAll", query="SELECT COUNT(x) FROM DivisionEntity x" )
} )
public class DivisionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", length=45)
    private String     name         ;

	// "conferenceId" (column "Conference_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="division", targetEntity=TeamEntity.class)
    private List<TeamEntity> listOfTeam  ;

    @ManyToOne
    @JoinColumn(name="Conference_id", referencedColumnName="id")
    private ConferenceEntity conference  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DivisionEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfTeam( List<TeamEntity> listOfTeam ) {
        this.listOfTeam = listOfTeam;
    }
    public List<TeamEntity> getListOfTeam() {
        return this.listOfTeam;
    }

    public void setConference( ConferenceEntity conference ) {
        this.conference = conference;
    }
    public ConferenceEntity getConference() {
        return this.conference;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
    	return this.name;
    } 

}
