/*
 * Created on 5 Jun 2016 ( Time 14:55:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.kumasi.mynfl.domain.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "Player_Status"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="Player_Status", catalog="nfldb" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PlayerStatusEntity.countAll", query="SELECT COUNT(x) FROM PlayerStatusEntity x" )
} )
public class PlayerStatusEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private PlayerStatusEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="code", length=45)
    private String     code         ;

    @Column(name="name", length=45)
    private String     name         ;

    @Column(name="description", length=2000)
    private String     description  ;

	// "playerId" (column "Player_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="Player_id", referencedColumnName="id")
    private PlayerEntity player      ;

    @ManyToOne
    @JoinColumn(name="Status_id", referencedColumnName="id", insertable=false, updatable=false)
    private StatusEntity status      ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PlayerStatusEntity() {
		super();
		this.compositePrimaryKey = new PlayerStatusEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.compositePrimaryKey.setId( id ) ;
    }
    public Integer getId() {
        return this.compositePrimaryKey.getId() ;
    }
    public void setStatusId( Integer statusId ) {
        this.compositePrimaryKey.setStatusId( statusId ) ;
    }
    public Integer getStatusId() {
        return this.compositePrimaryKey.getStatusId() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : code ( VARCHAR ) 
    public void setCode( String code ) {
        this.code = code;
    }
    public String getCode() {
        return this.code;
    }

    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : description ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setPlayer( PlayerEntity player ) {
        this.player = player;
    }
    public PlayerEntity getPlayer() {
        return this.player;
    }

    public void setStatus( StatusEntity status ) {
        this.status = status;
    }
    public StatusEntity getStatus() {
        return this.status;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
    	return this.name;
    } 

}
