/*
 * Created on 5 Jun 2016 ( Time 14:55:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service;

import java.util.List;

import com.kumasi.mynfl.domain.DraftRound;

/**
 * Business Service Interface for entity DraftRound.
 */
public interface DraftRoundService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	DraftRound findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<DraftRound> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	DraftRound save(DraftRound entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	DraftRound update(DraftRound entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	DraftRound create(DraftRound entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
