/*
 * Created on 5 Jun 2016 ( Time 14:55:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service;

import java.util.List;

import com.kumasi.mynfl.domain.DraftTeam;

/**
 * Business Service Interface for entity DraftTeam.
 */
public interface DraftTeamService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	DraftTeam findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<DraftTeam> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	DraftTeam save(DraftTeam entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	DraftTeam update(DraftTeam entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	DraftTeam create(DraftTeam entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
