/*
 * Created on 5 Jun 2016 ( Time 14:55:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service;

import java.util.List;

import com.kumasi.mynfl.domain.Draft;

/**
 * Business Service Interface for entity Draft.
 */
public interface DraftService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Draft findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Draft> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Draft save(Draft entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Draft update(Draft entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Draft create(Draft entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
