/*
 * Created on 5 Jun 2016 ( Time 14:55:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service;

import java.util.List;

import com.kumasi.mynfl.domain.DraftType;

/**
 * Business Service Interface for entity DraftType.
 */
public interface DraftTypeService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	DraftType findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<DraftType> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	DraftType save(DraftType entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	DraftType update(DraftType entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	DraftType create(DraftType entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
