/*
 * Created on 5 Jun 2016 ( Time 14:55:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service;

import java.util.List;

import com.kumasi.mynfl.domain.PlayerStat;

/**
 * Business Service Interface for entity PlayerStat.
 */
public interface PlayerStatService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	PlayerStat findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<PlayerStat> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	PlayerStat save(PlayerStat entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	PlayerStat update(PlayerStat entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	PlayerStat create(PlayerStat entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
