/*
 * Created on 5 Jun 2016 ( Time 14:55:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service;

import java.util.List;

import com.kumasi.mynfl.domain.Player;

/**
 * Business Service Interface for entity Player.
 */
public interface PlayerService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Player findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Player> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Player save(Player entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Player update(Player entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Player create(Player entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
