/*
 * Created on 5 Jun 2016 ( Time 14:55:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service;

import java.util.List;

import com.kumasi.mynfl.domain.PlayerPosition;

/**
 * Business Service Interface for entity PlayerPosition.
 */
public interface PlayerPositionService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	PlayerPosition findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<PlayerPosition> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	PlayerPosition save(PlayerPosition entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	PlayerPosition update(PlayerPosition entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	PlayerPosition create(PlayerPosition entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
