/*
 * Created on 5 Jun 2016 ( Time 14:55:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service;

import java.util.List;

import com.kumasi.mynfl.domain.Schedule;

/**
 * Business Service Interface for entity Schedule.
 */
public interface ScheduleService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Schedule findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Schedule> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Schedule save(Schedule entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Schedule update(Schedule entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Schedule create(Schedule entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
