/*
 * Created on 5 Jun 2016 ( Time 14:55:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.kumasi.mynfl.domain.DraftType;
import com.kumasi.mynfl.business.service.DraftTypeService;
import com.kumasi.mynfl.web.listitem.DraftTypeListItem;

/**
 * Spring MVC controller for 'DraftType' management.
 */
@Controller
public class DraftTypeRestController {

	@Resource
	private DraftTypeService draftTypeService;
	
	@RequestMapping( value="/items/draftType",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<DraftTypeListItem> findAllAsListItems() {
		List<DraftType> list = draftTypeService.findAll();
		List<DraftTypeListItem> items = new LinkedList<DraftTypeListItem>();
		for ( DraftType draftType : list ) {
			items.add(new DraftTypeListItem( draftType ) );
		}
		return items;
	}
	
	@RequestMapping( value="/draftType",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<DraftType> findAll() {
		return draftTypeService.findAll();
	}

	@RequestMapping( value="/draftType/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public DraftType findOne(@PathVariable("id") Integer id) {
		return draftTypeService.findById(id);
	}
	
	@RequestMapping( value="/draftType",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public DraftType create(@RequestBody DraftType draftType) {
		return draftTypeService.create(draftType);
	}

	@RequestMapping( value="/draftType/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public DraftType update(@PathVariable("id") Integer id, @RequestBody DraftType draftType) {
		return draftTypeService.update(draftType);
	}

	@RequestMapping( value="/draftType/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		draftTypeService.delete(id);
	}
	
}
