/*
 * Created on 5 Jun 2016 ( Time 14:55:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.kumasi.mynfl.domain.PlayerStatus;
import com.kumasi.mynfl.business.service.PlayerStatusService;
import com.kumasi.mynfl.web.listitem.PlayerStatusListItem;

/**
 * Spring MVC controller for 'PlayerStatus' management.
 */
@Controller
public class PlayerStatusRestController {

	@Resource
	private PlayerStatusService playerStatusService;
	
	@RequestMapping( value="/items/playerStatus",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<PlayerStatusListItem> findAllAsListItems() {
		List<PlayerStatus> list = playerStatusService.findAll();
		List<PlayerStatusListItem> items = new LinkedList<PlayerStatusListItem>();
		for ( PlayerStatus playerStatus : list ) {
			items.add(new PlayerStatusListItem( playerStatus ) );
		}
		return items;
	}
	
	@RequestMapping( value="/playerStatus",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<PlayerStatus> findAll() {
		return playerStatusService.findAll();
	}

	@RequestMapping( value="/playerStatus/{id}/{statusId}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public PlayerStatus findOne(@PathVariable("id") Integer id, @PathVariable("statusId") Integer statusId) {
		return playerStatusService.findById(id, statusId);
	}
	
	@RequestMapping( value="/playerStatus",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public PlayerStatus create(@RequestBody PlayerStatus playerStatus) {
		return playerStatusService.create(playerStatus);
	}

	@RequestMapping( value="/playerStatus/{id}/{statusId}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public PlayerStatus update(@PathVariable("id") Integer id, @PathVariable("statusId") Integer statusId, @RequestBody PlayerStatus playerStatus) {
		return playerStatusService.update(playerStatus);
	}

	@RequestMapping( value="/playerStatus/{id}/{statusId}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id, @PathVariable("statusId") Integer statusId) {
		playerStatusService.delete(id, statusId);
	}
	
}
