/*
 * Created on 5 Jun 2016 ( Time 14:55:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.kumasi.mynfl.domain.Team;
import com.kumasi.mynfl.business.service.TeamService;
import com.kumasi.mynfl.web.listitem.TeamListItem;

/**
 * Spring MVC controller for 'Team' management.
 */
@Controller
public class TeamRestController {

	@Resource
	private TeamService teamService;
	
	@RequestMapping( value="/items/team",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<TeamListItem> findAllAsListItems() {
		List<Team> list = teamService.findAll();
		List<TeamListItem> items = new LinkedList<TeamListItem>();
		for ( Team team : list ) {
			items.add(new TeamListItem( team ) );
		}
		return items;
	}
	
	@RequestMapping( value="/team",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Team> findAll() {
		return teamService.findAll();
	}

	@RequestMapping( value="/team/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Team findOne(@PathVariable("id") Integer id) {
		return teamService.findById(id);
	}
	
	@RequestMapping( value="/team",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Team create(@RequestBody Team team) {
		return teamService.create(team);
	}

	@RequestMapping( value="/team/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Team update(@PathVariable("id") Integer id, @RequestBody Team team) {
		return teamService.update(team);
	}

	@RequestMapping( value="/team/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		teamService.delete(id);
	}
	
}
