/*
 * Created on 5 Jun 2016 ( Time 14:55:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.kumasi.mynfl.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import com.kumasi.mynfl.domain.jpa.PlayerStatusEntity;
import com.kumasi.mynfl.domain.jpa.PlayerStatusEntityKey;
import com.kumasi.mynfl.persistence.commons.jpa.GenericJpaService;
import com.kumasi.mynfl.persistence.commons.jpa.JpaOperation;
import com.kumasi.mynfl.persistence.services.PlayerStatusPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "PlayerStatus" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class PlayerStatusPersistenceJPA extends GenericJpaService<PlayerStatusEntity, PlayerStatusEntityKey> implements PlayerStatusPersistence {

	/**
	 * Constructor
	 */
	public PlayerStatusPersistenceJPA() {
		super(PlayerStatusEntity.class);
	}

	@Override
	public PlayerStatusEntity load( Integer id, Integer statusId ) {
		// Build the composite key
		PlayerStatusEntityKey key = new PlayerStatusEntityKey( id, statusId );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer id, Integer statusId ) {
		// Build the composite key
		PlayerStatusEntityKey key = new PlayerStatusEntityKey( id, statusId );
		return super.delete( key );
	}

	@Override
	public boolean delete(PlayerStatusEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			PlayerStatusEntityKey key = new PlayerStatusEntityKey( entity.getId(), entity.getStatusId() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("PlayerStatusEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
