/*
 * Created on 5 Jun 2016 ( Time 14:55:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.kumasi.mynfl.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import com.kumasi.mynfl.domain.jpa.TeamStatEntity;
import com.kumasi.mynfl.persistence.commons.jpa.GenericJpaService;
import com.kumasi.mynfl.persistence.commons.jpa.JpaOperation;
import com.kumasi.mynfl.persistence.services.TeamStatPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "TeamStat" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class TeamStatPersistenceJPA extends GenericJpaService<TeamStatEntity, Integer> implements TeamStatPersistence {

	/**
	 * Constructor
	 */
	public TeamStatPersistenceJPA() {
		super(TeamStatEntity.class);
	}

	@Override
	public TeamStatEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(TeamStatEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("TeamStatEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
