/*
 * Created on 5 Jun 2016 ( Time 14:55:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.domain;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Player implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@NotNull
	private Integer id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Size(max = 45)
	private String firstName;

	@Size(max = 45)
	private String lastName;

	private Date dateOfBirth;

	@Size(max = 45)
	private String college;

	@Size(max = 45)
	private String draftPosition;

	private Integer yearSelected;

	private Date dateSigned;

	@NotNull
	private Integer playerPositionId;

	@NotNull
	private Integer teamId;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setCollege(String college) {
		this.college = college;
	}

	public String getCollege() {
		return this.college;
	}

	public void setDraftPosition(String draftPosition) {
		this.draftPosition = draftPosition;
	}

	public String getDraftPosition() {
		return this.draftPosition;
	}

	public void setYearSelected(Integer yearSelected) {
		this.yearSelected = yearSelected;
	}

	public Integer getYearSelected() {
		return this.yearSelected;
	}

	public void setDateSigned(Date dateSigned) {
		this.dateSigned = dateSigned;
	}

	public Date getDateSigned() {
		return this.dateSigned;
	}

	public void setPlayerPositionId(Integer playerPositionId) {
		this.playerPositionId = playerPositionId;
	}

	public Integer getPlayerPositionId() {
		return this.playerPositionId;
	}

	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	public Integer getTeamId() {
		return this.teamId;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------

	public String toString() {
		return this.firstName + " " + this.lastName;
	}

}
