/*
 * Created on 5 Jun 2016 ( Time 14:55:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.domain;

import java.io.Serializable;

import javax.validation.constraints.*;

public class TeamStat implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@NotNull
	private Integer id;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------

	private Integer won;

	private Integer lost;

	private Integer tied;

	private Float percent;

	private Integer pointsForced;

	private Integer pointsAllowed;

	private Integer netPints;

	private Integer touchdowns;

	@Size(max = 5)
	private String homeRecord;

	@Size(max = 5)
	private String roadRecord;

	@Size(max = 5)
	private String divisionRecord;

	@Size(max = 5)
	private String conferenceRecord;

	@Size(max = 45)
	private String playerStatscol;

	private Float overallPercent;

	@Size(max = 45)
	private String streak;

	@Size(max = 5)
	private String lastFive;

	@NotNull
	private Integer teamId;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	public void setWon(Integer won) {
		this.won = won;
	}

	public Integer getWon() {
		return this.won;
	}

	public void setLost(Integer lost) {
		this.lost = lost;
	}

	public Integer getLost() {
		return this.lost;
	}

	public void setTied(Integer tied) {
		this.tied = tied;
	}

	public Integer getTied() {
		return this.tied;
	}

	public void setPercent(Float percent) {
		this.percent = percent;
	}

	public Float getPercent() {
		return this.percent;
	}

	public void setPointsForced(Integer pointsForced) {
		this.pointsForced = pointsForced;
	}

	public Integer getPointsForced() {
		return this.pointsForced;
	}

	public void setPointsAllowed(Integer pointsAllowed) {
		this.pointsAllowed = pointsAllowed;
	}

	public Integer getPointsAllowed() {
		return this.pointsAllowed;
	}

	public void setNetPints(Integer netPints) {
		this.netPints = netPints;
	}

	public Integer getNetPints() {
		return this.netPints;
	}

	public void setTouchdowns(Integer touchdowns) {
		this.touchdowns = touchdowns;
	}

	public Integer getTouchdowns() {
		return this.touchdowns;
	}

	public void setHomeRecord(String homeRecord) {
		this.homeRecord = homeRecord;
	}

	public String getHomeRecord() {
		return this.homeRecord;
	}

	public void setRoadRecord(String roadRecord) {
		this.roadRecord = roadRecord;
	}

	public String getRoadRecord() {
		return this.roadRecord;
	}

	public void setDivisionRecord(String divisionRecord) {
		this.divisionRecord = divisionRecord;
	}

	public String getDivisionRecord() {
		return this.divisionRecord;
	}

	public void setConferenceRecord(String conferenceRecord) {
		this.conferenceRecord = conferenceRecord;
	}

	public String getConferenceRecord() {
		return this.conferenceRecord;
	}

	public void setPlayerStatscol(String playerStatscol) {
		this.playerStatscol = playerStatscol;
	}

	public String getPlayerStatscol() {
		return this.playerStatscol;
	}

	public void setOverallPercent(Float overallPercent) {
		this.overallPercent = overallPercent;
	}

	public Float getOverallPercent() {
		return this.overallPercent;
	}

	public void setStreak(String streak) {
		this.streak = streak;
	}

	public String getStreak() {
		return this.streak;
	}

	public void setLastFive(String lastFive) {
		this.lastFive = lastFive;
	}

	public String getLastFive() {
		return this.lastFive;
	}

	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	public Integer getTeamId() {
		return this.teamId;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------

	public String toString() {
		return this.id.toString();
	}

}
