/*
 * Created on 5 Jun 2016 ( Time 14:55:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.mynfl.domain.Draft;
import com.kumasi.mynfl.domain.jpa.DraftEntity;
import com.kumasi.mynfl.domain.jpa.DraftTypeEntity;
import com.kumasi.mynfl.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class DraftServiceMapperTest {

	private DraftServiceMapper draftServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		draftServiceMapper = new DraftServiceMapper();
		draftServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'DraftEntity' to 'Draft'
	 * @param draftEntity
	 */
	@Test
	public void testMapDraftEntityToDraft() {
		// Given
		DraftEntity draftEntity = new DraftEntity();
		draftEntity.setYear(mockValues.nextInteger());
		draftEntity.setDraftType(new DraftTypeEntity());
		draftEntity.getDraftType().setId(mockValues.nextInteger());
		
		// When
		Draft draft = draftServiceMapper.mapDraftEntityToDraft(draftEntity);
		
		// Then
		assertEquals(draftEntity.getYear(), draft.getYear());
		assertEquals(draftEntity.getDraftType().getId(), draft.getDraftTypeId());
	}
	
	/**
	 * Test : Mapping from 'Draft' to 'DraftEntity'
	 */
	@Test
	public void testMapDraftToDraftEntity() {
		// Given
		Draft draft = new Draft();
		draft.setYear(mockValues.nextInteger());
		draft.setDraftTypeId(mockValues.nextInteger());

		DraftEntity draftEntity = new DraftEntity();
		
		// When
		draftServiceMapper.mapDraftToDraftEntity(draft, draftEntity);
		
		// Then
		assertEquals(draft.getYear(), draftEntity.getYear());
		assertEquals(draft.getDraftTypeId(), draftEntity.getDraftType().getId());
	}

}