/*
 * Created on 5 Jun 2016 ( Time 14:55:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.kumasi.mynfl.domain.ScheduleType;
import com.kumasi.mynfl.domain.jpa.ScheduleTypeEntity;
import com.kumasi.mynfl.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class ScheduleTypeServiceMapperTest {

	private ScheduleTypeServiceMapper scheduleTypeServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		scheduleTypeServiceMapper = new ScheduleTypeServiceMapper();
		scheduleTypeServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'ScheduleTypeEntity' to 'ScheduleType'
	 * @param scheduleTypeEntity
	 */
	@Test
	public void testMapScheduleTypeEntityToScheduleType() {
		// Given
		ScheduleTypeEntity scheduleTypeEntity = new ScheduleTypeEntity();
		scheduleTypeEntity.setCode(mockValues.nextString(45));
		scheduleTypeEntity.setDescription(mockValues.nextString(45));
		
		// When
		ScheduleType scheduleType = scheduleTypeServiceMapper.mapScheduleTypeEntityToScheduleType(scheduleTypeEntity);
		
		// Then
		assertEquals(scheduleTypeEntity.getCode(), scheduleType.getCode());
		assertEquals(scheduleTypeEntity.getDescription(), scheduleType.getDescription());
	}
	
	/**
	 * Test : Mapping from 'ScheduleType' to 'ScheduleTypeEntity'
	 */
	@Test
	public void testMapScheduleTypeToScheduleTypeEntity() {
		// Given
		ScheduleType scheduleType = new ScheduleType();
		scheduleType.setCode(mockValues.nextString(45));
		scheduleType.setDescription(mockValues.nextString(45));

		ScheduleTypeEntity scheduleTypeEntity = new ScheduleTypeEntity();
		
		// When
		scheduleTypeServiceMapper.mapScheduleTypeToScheduleTypeEntity(scheduleType, scheduleTypeEntity);
		
		// Then
		assertEquals(scheduleType.getCode(), scheduleTypeEntity.getCode());
		assertEquals(scheduleType.getDescription(), scheduleTypeEntity.getDescription());
	}

}