
/*
 * Created on 5 Jun 2016 ( Time 14:55:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.mynfl.domain.jpa.DraftRoundEntity;
import com.kumasi.mynfl.mock.tool.MockValues;

public class DraftRoundEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public DraftRoundEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public DraftRoundEntity createInstance( Integer id ) {
		DraftRoundEntity entity = new DraftRoundEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setRoundNbr( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setPlayerName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPlayerPosition( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setPlayerAnalysis( mockValues.nextString(16777215) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setDraftTeam( TODO ) ; // DraftTeam 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<DraftRoundEntity> createList(int count) {
		List<DraftRoundEntity> list = new LinkedList<DraftRoundEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
