
/*
 * Created on 5 Jun 2016 ( Time 14:55:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.mynfl.domain.jpa.PlayerEntity;
import com.kumasi.mynfl.mock.tool.MockValues;

public class PlayerEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public PlayerEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public PlayerEntity createInstance( Integer id ) {
		PlayerEntity entity = new PlayerEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setFirstName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setLastName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setDateOfBirth( mockValues.nextDate() ) ; // java.util.Date 
		entity.setCollege( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setDraftPosition( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setYearSelected( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setDateSigned( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setListOfPlayerStat( TODO ) ; // List<PlayerStat> 
		// setPlayerPosition( TODO ) ; // PlayerPosition 
		// setTeam( TODO ) ; // Team 
		// setListOfPlayerStatus( TODO ) ; // List<PlayerStatus> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<PlayerEntity> createList(int count) {
		List<PlayerEntity> list = new LinkedList<PlayerEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
