
/*
 * Created on 5 Jun 2016 ( Time 14:55:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.mynfl.domain.jpa.PlayerStatEntity;
import com.kumasi.mynfl.mock.tool.MockValues;

public class PlayerStatEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public PlayerStatEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public PlayerStatEntity createInstance( Integer id ) {
		PlayerStatEntity entity = new PlayerStatEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setPlayerType( mockValues.nextString(2) ) ; // java.lang.String 
		entity.setRushingAttempts( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setPassingAttempts( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setPassingCompletions( mockValues.nextFloat() ) ; // java.lang.Float 
		entity.setYardsPerCarry( mockValues.nextFloat() ) ; // java.lang.Float 
		entity.setYardsPerPass( mockValues.nextFloat() ) ; // java.lang.Float 
		entity.setYardsPerCatch( mockValues.nextFloat() ) ; // java.lang.Float 
		entity.setTouchdowns( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setNbrInterceptions( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setNbrTackles( mockValues.nextFloat() ) ; // java.lang.Float 
		entity.setNbrSacks( mockValues.nextFloat() ) ; // java.lang.Float 
		entity.setNbrAssists( mockValues.nextFloat() ) ; // java.lang.Float 
		entity.setOpponent( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setGameDate( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setPlayer( TODO ) ; // Player 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<PlayerStatEntity> createList(int count) {
		List<PlayerStatEntity> list = new LinkedList<PlayerStatEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
