
/*
 * Created on 5 Jun 2016 ( Time 14:55:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.mynfl.domain.jpa.PlayerPositionEntity;
import com.kumasi.mynfl.mock.tool.MockValues;

public class PlayerPositionEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public PlayerPositionEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public PlayerPositionEntity createInstance( Integer id ) {
		PlayerPositionEntity entity = new PlayerPositionEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setPositionName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setDescription( mockValues.nextString(500) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfPlayer( TODO ) ; // List<Player> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<PlayerPositionEntity> createList(int count) {
		List<PlayerPositionEntity> list = new LinkedList<PlayerPositionEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
