
/*
 * Created on 5 Jun 2016 ( Time 14:55:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.kumasi.mynfl.mock;

import java.util.LinkedList;
import java.util.List;

import com.kumasi.mynfl.domain.jpa.TeamEntity;
import com.kumasi.mynfl.mock.tool.MockValues;

public class TeamEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public TeamEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public TeamEntity createInstance( Integer id ) {
		TeamEntity entity = new TeamEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setCode( mockValues.nextString(3) ) ; // java.lang.String 
		entity.setName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setCity( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setState( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setStadium( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setOwner( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setHeadCoach( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setDivision( TODO ) ; // Division 
		// setListOfSchedule( TODO ) ; // List<Schedule> 
		// setListOfPlayer( TODO ) ; // List<Player> 
		// setListOfTeamStat( TODO ) ; // List<TeamStat> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<TeamEntity> createList(int count) {
		List<TeamEntity> list = new LinkedList<TeamEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
